/**
 * Invoice Controller
 * 
 * Handles invoice/receipt CRUD and PDF generation with QR codes.
 * Invoices are auto-created when orders are completed and can also be
 * manually generated by admins.
 */

import { RequestHandler } from 'express';
import Invoice from '../models/invoice.model';
import Order from '../models/order.model';
import User from '../models/user.model';
import WhiteLabel from '../models/white-label.model';
import { AuthRequest } from '../middleware/auth.middleware';
import { CustomError } from '../middleware/error.middleware';
import { logger } from '../utils/logger';
import {
  generateInvoicePDF,
  generateQRCode,
  generateInvoiceEmailHTML,
  InvoiceData,
} from '../utils/invoice.service';
import { sendEmail } from '../utils/email';

/**
 * Build InvoiceData from an Order and tenant config
 */
async function buildInvoiceDataFromOrder(
  order: any,
  tenant: string,
  type: 'invoice' | 'receipt',
  verificationToken: string,
  invoiceNumber: string
): Promise<InvoiceData> {
  const tenantConfig = await WhiteLabel.findOne({ tenantId: tenant, isActive: true });
  const user = await User.findById(order.user);

  const fromName = tenantConfig?.name || 'ComSpace Store';
  const fromEmail = tenantConfig?.contact?.email || process.env.EMAIL_FROM || 'noreply@comspace.com';

  return {
    invoiceNumber,
    verificationToken,
    type,
    issuedAt: new Date(),
    from: {
      name: fromName,
      email: fromEmail,
      phone: tenantConfig?.contact?.phone,
      address: tenantConfig?.contact?.address,
      logo: tenantConfig?.branding?.logo,
    },
    to: {
      name: `${user?.firstName || ''} ${user?.lastName || ''}`.trim() || 'Customer',
      email: user?.email || '',
      phone: user?.phone,
      address: order.deliveryAddress
        ? `${order.deliveryAddress.street}, ${order.deliveryAddress.city}, ${order.deliveryAddress.state} ${order.deliveryAddress.postalCode}, ${order.deliveryAddress.country}`
        : undefined,
    },
    items: order.items.map((item: any) => ({
      description: item.name,
      quantity: item.quantity,
      unitPrice: item.price,
      total: item.price * item.quantity,
      sku: item.sku,
    })),
    subtotal: order.subtotal,
    taxRate: order.subtotal > 0 ? order.tax / order.subtotal : 0,
    taxAmount: order.tax,
    shippingFee: order.shippingFee,
    discount: order.discount || 0,
    total: order.total,
    currency: order.currency,
    paymentMethod: order.paymentMethod,
    paymentIntentId: order.paymentIntentId,
    paidAt: order.paymentStatus === 'completed' ? new Date() : undefined,
    orderNumber: order.orderNumber,
    branding: {
      primaryColor: tenantConfig?.branding?.primaryColor || '#9333ea',
      storeName: tenantConfig?.name || 'ComSpace',
    },
  };
}

/**
 * Create invoice/receipt for an order (called internally after order creation or payment)
 */
export async function createInvoiceForOrder(
  orderId: string,
  tenant: string,
  type: 'invoice' | 'receipt' = 'invoice'
): Promise<typeof Invoice.prototype | null> {
  try {
    // Check if invoice already exists for this order
    const existing = await Invoice.findOne({ order: orderId, tenant, type });
    if (existing) {
      logger.info(`Invoice already exists for order ${orderId}: ${existing.invoiceNumber}`);
      return existing;
    }

    const order = await Order.findById(orderId);
    if (!order) {
      logger.error(`Cannot create invoice: order ${orderId} not found`);
      return null;
    }

    // Create the invoice document (pre-save hook generates number + token)
    const invoice = new Invoice({
      order: order._id,
      user: order.user,
      tenant,
      type,
      status: type === 'receipt' ? 'paid' : 'issued',
      from: { name: 'Pending', email: 'pending@comspace.com' }, // Will be overwritten
      to: { name: 'Pending', email: 'pending@comspace.com' },
      items: [],
      subtotal: order.subtotal,
      taxAmount: order.tax,
      shippingFee: order.shippingFee,
      discount: order.discount || 0,
      total: order.total,
      currency: order.currency,
      paymentMethod: order.paymentMethod,
      paymentIntentId: order.paymentIntentId,
      paidAt: order.paymentStatus === 'completed' ? new Date() : undefined,
    });

    await invoice.save();

    // Now build full invoice data and update the document
    const invoiceData = await buildInvoiceDataFromOrder(
      order,
      tenant,
      type,
      invoice.verificationToken,
      invoice.invoiceNumber
    );

    // Update with proper from/to/items
    invoice.from = invoiceData.from;
    invoice.to = invoiceData.to;
    invoice.items = invoiceData.items;
    invoice.taxRate = invoiceData.taxRate;

    // Generate QR code data URL
    const qrCodeDataUrl = await generateQRCode(invoice.verificationToken);
    invoice.qrCodeDataUrl = qrCodeDataUrl;

    // Generate PDF
    try {
      const { filePath, fileName } = await generateInvoicePDF(invoiceData);
      invoice.pdfUrl = `/uploads/invoices/${fileName}`;
      invoice.pdfStorage = 'local';
      logger.info(`Invoice PDF generated: ${filePath}`);
    } catch (pdfError) {
      logger.error('PDF generation failed (invoice still created):', pdfError);
    }

    await invoice.save();

    // Send invoice email to customer
    try {
      const emailHtml = generateInvoiceEmailHTML(invoiceData, qrCodeDataUrl);
      await sendEmail({
        to: invoiceData.to.email,
        subject: `${type === 'receipt' ? 'Receipt' : 'Invoice'} #${invoice.invoiceNumber} — ${invoiceData.branding?.storeName || 'ComSpace'}`,
        html: emailHtml,
      });
      logger.info(`Invoice email sent to ${invoiceData.to.email}`);

      // Also send to the merchant/business
      if (invoiceData.from.email && invoiceData.from.email !== invoiceData.to.email) {
        await sendEmail({
          to: invoiceData.from.email,
          subject: `[Copy] ${type === 'receipt' ? 'Receipt' : 'Invoice'} #${invoice.invoiceNumber} — Order #${order.orderNumber}`,
          html: emailHtml,
        });
        logger.info(`Invoice copy sent to merchant: ${invoiceData.from.email}`);
      }
    } catch (emailError) {
      logger.error('Invoice email failed (invoice still created):', emailError);
    }

    return invoice;
  } catch (error) {
    logger.error('Invoice creation failed:', error);
    return null;
  }
}

// ── REST Handlers ──

/**
 * GET /api/invoices — List invoices for the current user
 */
export const getMyInvoices: RequestHandler = async (req, res, next) => {
  const authReq = req as AuthRequest;
  try {
    const { page = 1, limit = 10, type } = req.query;
    const query: any = { user: authReq.user!._id, tenant: authReq.tenant };
    if (type) query.type = type;

    const limitNum = Math.min(Number(limit) || 10, 100);
    const skip = (Number(page) - 1) * limitNum;

    const [invoices, total] = await Promise.all([
      Invoice.find(query).sort('-createdAt').skip(skip).limit(limitNum),
      Invoice.countDocuments(query),
    ]);

    res.status(200).json({
      success: true,
      data: {
        invoices,
        pagination: { page: Number(page), limit: limitNum, total, pages: Math.ceil(total / limitNum) },
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/:id — Get single invoice
 */
export const getInvoice: RequestHandler = async (req, res, next) => {
  const authReq = req as AuthRequest;
  try {
    const invoice = await Invoice.findOne({
      _id: req.params.id,
      tenant: authReq.tenant,
    }).populate('order');

    if (!invoice) {
      return next(new CustomError('Invoice not found', 404));
    }

    // Non-admin users can only see their own invoices
    if (
      !['superadmin', 'admin', 'admin1', 'admin2', 'merchant'].includes(authReq.user?.role || '') &&
      invoice.user.toString() !== authReq.user!._id.toString()
    ) {
      return next(new CustomError('Not authorized', 403));
    }

    res.status(200).json({ success: true, data: { invoice } });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/:id/download — Download invoice PDF
 */
export const downloadInvoice: RequestHandler = async (req, res, next) => {
  const authReq = req as AuthRequest;
  try {
    const invoice = await Invoice.findOne({
      _id: req.params.id,
      tenant: authReq.tenant,
    });

    if (!invoice) {
      return next(new CustomError('Invoice not found', 404));
    }

    // Authorization check
    if (
      !['superadmin', 'admin', 'admin1', 'admin2', 'merchant'].includes(authReq.user?.role || '') &&
      invoice.user.toString() !== authReq.user!._id.toString()
    ) {
      return next(new CustomError('Not authorized', 403));
    }

    // If PDF exists on disk, stream it
    if (invoice.pdfUrl && invoice.pdfStorage === 'local') {
      const path = require('path');
      const fs = require('fs');
      const filePath = path.join(__dirname, '..', '..', invoice.pdfUrl);
      
      if (fs.existsSync(filePath)) {
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${invoice.invoiceNumber}.pdf"`);
        return fs.createReadStream(filePath).pipe(res);
      }
    }

    // Regenerate PDF on-the-fly if file is missing
    const order = await Order.findById(invoice.order);
    if (!order) {
      return next(new CustomError('Associated order not found', 404));
    }

    const invoiceData = await buildInvoiceDataFromOrder(
      order,
      authReq.tenant || 'default',
      invoice.type as 'invoice' | 'receipt',
      invoice.verificationToken,
      invoice.invoiceNumber
    );

    const { buffer, fileName } = await generateInvoicePDF(invoiceData);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    res.send(buffer);
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/verify/:token — Public verification endpoint
 * Returns invoice details for QR code scans (no auth required)
 */
export const verifyInvoice: RequestHandler = async (req, res, next) => {
  try {
    const { token } = req.params;

    const invoice = await Invoice.findOne({ verificationToken: token })
      .select('invoiceNumber type status from.name to.name total currency issuedAt paidAt orderNumber items.description items.quantity items.total');

    if (!invoice) {
      return res.status(404).json({
        success: false,
        verified: false,
        message: 'Invoice not found. This QR code may be invalid.',
      });
    }

    return res.status(200).json({
      success: true,
      verified: true,
      data: {
        invoiceNumber: invoice.invoiceNumber,
        type: invoice.type,
        status: invoice.status,
        merchant: (invoice as any).from?.name,
        customer: (invoice as any).to?.name,
        total: invoice.total,
        currency: invoice.currency,
        issuedAt: invoice.issuedAt,
        paidAt: invoice.paidAt,
        itemCount: invoice.items?.length || 0,
      },
    });
  } catch (error) {
    return next(error);
  }
};

/**
 * POST /api/invoices/generate/:orderId — Admin: manually generate invoice for an order
 */
export const generateInvoiceForOrder: RequestHandler = async (req, res, next) => {
  const authReq = req as AuthRequest;
  try {
    const { orderId } = req.params;
    const { type = 'invoice' } = req.body;

    const order = await Order.findOne({ _id: orderId, tenant: authReq.tenant });
    if (!order) {
      return next(new CustomError('Order not found', 404));
    }

    const invoice = await createInvoiceForOrder(
      order._id.toString(),
      authReq.tenant || 'default',
      type
    );

    if (!invoice) {
      return next(new CustomError('Invoice generation failed', 500));
    }

    res.status(201).json({ success: true, data: { invoice } });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /api/invoices/admin/all — Admin: list all invoices for the tenant
 */
export const getAllInvoices: RequestHandler = async (req, res, next) => {
  const authReq = req as AuthRequest;
  try {
    const { page = 1, limit = 20, type, status } = req.query;
    const query: any = { tenant: authReq.tenant };
    if (type) query.type = type;
    if (status) query.status = status;

    const limitNum = Math.min(Number(limit) || 20, 100);
    const skip = (Number(page) - 1) * limitNum;

    const [invoices, total] = await Promise.all([
      Invoice.find(query)
        .sort('-createdAt')
        .skip(skip)
        .limit(limitNum)
        .populate('user', 'firstName lastName email')
        .populate('order', 'orderNumber status'),
      Invoice.countDocuments(query),
    ]);

    res.status(200).json({
      success: true,
      data: {
        invoices,
        pagination: { page: Number(page), limit: limitNum, total, pages: Math.ceil(total / limitNum) },
      },
    });
  } catch (error) {
    next(error);
  }
};
